### ISSUE TITLE
Start in user home

### ISSUE THREAD

**Issue by fpqc** [rprichard/wslbridge#2]
Hi, wondering if you can tell the wslbridge to start in the user's home.

The built-in bash.exe in system32 allows you to start it with
`bash.exe ~ -c "linux program to start"`

Is there a way to start the wslbridge in a specific lxss directory?

**Comment by mintty** [comment]
I was about to ask the same, caused by the discussion in https://github.com/mintty/wsltty/issues/3

**Comment by fpqc** [comment]
@mintty I know. I realized that the correct place to ask was upstream here.

**Comment by rprichard** [comment]
I think I agree that there should be some option for controlling the start dir.

**Comment by fpqc** [comment]
@rprichard By the way, this project is amazing.Was wondering if there is a way to make it work using ttys rather than ptys in WSL.

**Comment by rprichard** [comment]
@fpqc What do you mean by tty support?

Regarding the feature request, there are three kinds of paths wslbridge could accept for the startdir: a Windows path, a Cygwin path, or a WSL path.

My first instinct is that only WSL paths are worth handling -- the others can be accommodated by setting the starting directory before invoking wslbridge.  Maybe wslbridge could have a `-C<WSLPATH>` option.  If the first path component of `WSLPATH` is `~` or `~user`, wslbridge could replace it with the appropriate directory.  (Someone invoking wslbridge from Cygwin bash would have to be a bit careful.  Running `wslbridge -C ~` from bash would do the wrong thing, because Cygwin would interpret `~` before wslbridge.)

**Comment by rprichard** [comment]
wslbridge could *also* do things like substitute environment variables in `WSLPATH`, but that strikes me as unnecessary.

**Comment by fpqc** [comment]
@rprichard Only one worth doing is a WSL path.  The other two can be legitimately achieved with the "start in" function of Windows.

**Comment by rprichard** [comment]
I added a -C option that changes the working directory before exec'ing the child process.  It has special code to interpret a `~` at the start, so passing `-C~` to wslbridge will start the child in the WSL home directory.

**Comment by fpqc** [comment]
Cool!
