### ISSUE TITLE
Feature Request: Add command option to mention backend file

### ISSUE THREAD

**Issue by Biswa96** [rprichard/wslbridge#23]
When I place the `wslbridge-backend` file not in the `wslbridge.exe` it shows an error. So, can you add a option to mention backend file path? 
Example: `C:\xyz\wslbridge.exe -p "C:\abc\wslbridge-backend"`

**Comment by rprichard** [comment]
Maybe the path to the backend should be a WSL path rather than a Windows path.

**Comment by Biswa96** [comment]
How can I mention that path in command line? Do you have any parameter in wslbridge?

**Comment by Biswa96** [comment]
How can I add the backend path in wslbridge command as I said above? The path of frontend and backend will  be different. This may help in my project of wsltty appx package.

**Comment by rprichard** [comment]
There isn't currently an option to specify a non-default path to the backend binary.

Your request shows a Windows path to the backend, but the frontend needs a WSL path to invoke the backend. Converting a Windows path to a WSL path has had trouble before (https://github.com/rprichard/wslbridge/issues/22), so I suggested that if wslbridge has an option, then maybe it should use a WSL path rather than a Windows path.

On the other hand, you could ensure that the two binaries are in the same directory.
